version: '3.8'

volumes:
  frontend:
    # external: true

services:
  gateway:
    build: ./gateway
    ports:
      - 80:80
    restart: always
    volumes:
      - frontend:/usr/share/nginx/html/

  frontend:
    build: ./frontend
    volumes:
      - frontend:/app/dist

  auth:
    build: ./auth
    restart: always
    depends_on:
      - auth_db
    environment:
      DATABASE_URL: postgresql://prisma:prisma@auth_db:5432/prisma
      TOKEN_AGE: 2h
      REFRESH_TOKEN_AGE: 3h
      DEBUG: 'jpg:*'
    command: sh -c "npx prisma db push && node ./bin/start.js"

  user:
    build: ./user
    restart: always
    depends_on:
      - user_db
    environment:
      DATABASE_URL: postgresql://prisma:prisma@user_db:5432/prisma
      BASE_URL: http://gateway/api
      DEBUG: jpg:*
    command: sh -c "npx prisma db push && node ./bin/start.js"

  post:
    build: ./post
    restart: always
    depends_on:
      - post_db
    environment:
      DATABASE_URL: postgresql://prisma:prisma@post_db:5432/prisma
      BASE_URL: http://gateway/api
      DEBUG: jpg:*
    command: sh -c "npx prisma db push && node ./bin/start.js"

  tag:
    build: ./tags
    restart: always
    depends_on:
      - tag_db
    environment:
      DATABASE_URL: postgresql://prisma:prisma@tag_db:5432/prisma
      BASE_URL: http://gateway/api
      DEBUG: jpg:*
    command: sh -c "npx prisma db push && node ./bin/start.js"

  auth_db:
    image: postgres:13
    restart: always
    ports:
      - '5000:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma

  user_db:
    image: postgres:13
    restart: always
    ports:
      - '5001:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma

  post_db:
    image: postgres:13
    restart: always
    ports:
      - '5002:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma

  tag_db:
    image: postgres:13
    restart: always
    ports:
      - '5003:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
